### ISSUE TITLE
7.2.2 - Search highlighting remains after exiting search

### ISSUE THREAD

**Issue by voidzone** [tullamods/Bagnon#543]
Typing in a search query and hitting escape closes the search box but keeps the query active.

**Comment by voidzone** [comment]
Also the search toggle icon remains permanently highlighted even after manually deleting your query.

**Comment by Jaliborc** [comment]
Fixed

**Comment by ssateneth** [comment]
Sorry, its not fixed. Now it wont search at all; you can enter in search terms, but no items are ever highlighted or filtered out.

**Comment by voidzone** [comment]
Confirmed @ssateneth's issue.
Doesn't trigger an LUA error.
