### ISSUE TITLE
bank does not visually update

### ISSUE THREAD

**Issue by Kanegasi** [tullamods/Bagnon#689]
When moving items in, out, or within the bank, the items themselves move but do not visually update their position. Closing and opening the bank updates the visuals.

**Comment by cipher3010** [comment]
In
Bagnon\components\components.xml

add two line

	<Script file="ownerSelector.lua"/>
	<Script file="playerSelector.lua"/>

**Comment by cipher3010** [comment]
Sorry。
Just add one line 。
<Script file="playerSelector.lua"/>
It works fine for me.

**Comment by dartraiden** [comment]
Should be fixed via https://github.com/tullamods/Bagnon/commit/8c1ab0fd62534cbd9f4667b152ca3ca02757935c

**Comment by Sembiance** [comment]
This is happening to me with 8.0.0 on one of my characters (but not all my characters)

Thankfully the code Kanegasi shared when pasted into Bagnon/main.lua fixes the problem.

**Comment by Sembiance** [comment]
I may have spoke too soon. Even with the code pasted into main.lua, I'm still having problems getting my bank to update.

I've downgraded to 8.0.0b as that doesn't appear to have any problems. Got it from: http://www.wowinterface.com/downloads/info4459-7.3.11.html#other
