### ISSUE TITLE
Add Scrap-O-Matic 1000 and Shred-Master Mk1 to frames that auto-open and close Bagnon

### ISSUE THREAD

**Issue by GnuclearGnome** [tullamods/Bagnon#781]
**Is your feature request related to a problem? Please describe.**
In as much as Bagnon needs to auto-close when leaving the scrapping frame, it is related to Issue #762.

**Describe the solution you'd like**
Add the Scrapping Frames to the Auto Display Options.  Could, perhaps, be added to the "Crafting" option.

**Comment by wtwilson3** [comment]
Absolutely.  Badly needed.

**Comment by Jaliborc** [comment]
Done

**Comment by wtwilson3** [comment]
@Jaliborc Sorry, this issue is not fixed.  Just tried the latest update at the Scrapper in Boralus and window did not open.  Checked settings and did not see a check box.
