### ISSUE TITLE
Leerenlager

### ISSUE THREAD

**Issue by riwin** [tullamods/Bagnon#804]
Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua:409: Usage: IsBattlePayItem(bag, slot)
Time: Tue Sep 11 00:01:13 2018
Count: 160
Stack: ...AddOns\Bagnon\external\Wildpants\components\item.lua:409: Usage: IsBattlePayItem(bag, slot)
[C]: in function `IsBattlePayItem'
...AddOns\Bagnon\external\Wildpants\components\item.lua:409: in function `IsPaid'
...AddOns\Bagnon\external\Wildpants\components\item.lua:252: in function `UpdateBorder'
...AddOns\Bagnon\external\Wildpants\components\item.lua:228: in function `Update'
...AddOns\Bagnon\external\Wildpants\components\item.lua:124: in function <...AddOns\Bagnon\external\Wildpants\components\item.lua:119>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:3134: in function `ShowUIPanel'
...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55: in function `ShowFrame'
Interface\AddOns\Bagnon_VoidStorage\main.lua:17: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `SendMessage'
...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:49: in function <...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:49>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: (*temporary) = "vault"
(*temporary) = 160

**Comment by dafergu2** [comment]
I fixed this locally by updating the following file:
`/Applications/World of Warcraft/Interface/AddOns/Bagnon_VoidStorage/components/item.lua`

I added this line to the very end:

`function ItemSlot:IsPaid() end`

I'm not sure if that's the long term fix, but it prevented the crash and I haven't yet noticed any side effects.  For some reason, that api doesn't like the implementation of the normal `ItemSlot:IsPaid` which calls the `IsBattlePayItem` api.  That api returns true if the item was bought from the battle.net store, so I figured it would be fine if I simply overrode the implementation of `IsPaid` so that the call to `IsBattlePayItem` didn't occur.

I'd really love to see the appropriate solution.  I did some rudimentary debugging (I've no experience with WoW development, so don't know the tool chain yet) and it appeared that `self:GetBag()` was returning 'vault' and it looked like the api didn't like that.

**Comment by jemmers** [comment]
> I fixed this locally by updating the following file:
> `/Applications/World of Warcraft/Interface/AddOns/Bagnon_VoidStorage/components/item.lua`
> 
> I added this line to the very end:
> 
> `function ItemSlot:IsPaid() end`
> 
> I'm not sure if that's the long term fix, but it prevented the crash and I haven't yet noticed any side effects. For some reason, that api doesn't like the implementation of the normal `ItemSlot:IsPaid` which calls the `IsBattlePayItem` api. That api returns true if the item was bought from the battle.net store, so I figured it would be fine if I simply overrode the implementation of `IsPaid` so that the call to `IsBattlePayItem` didn't occur.
> 
> I'd really love to see the appropriate solution. I did some rudimentary debugging (I've no experience with WoW development, so don't know the tool chain yet) and it appeared that `self:GetBag()` was returning 'vault' and it looked like the api didn't like that.

I tried this, and it did not fix my issue, but my issue is for the entire addon.  I hope it fixes it for that that just have the void storage issue.

**Comment by DasAoD** [comment]
Thanks. That did the trick, and my void storage is now ok.

**Comment by AlexL1118** [comment]
> function ItemSlot:IsPaid() end
Thanks, this solved the problem in my case.
